# 베이스 이미지 설정
FROM python:3.11-slim

# Java JDK 설치
RUN apt-get update && apt-get install -y \
    default-jdk \
    && apt-get clean


# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY requirements.txt .

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 파일 복사
COPY . .

# FastAPI를 실행할 명령 설정
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]